function [scenario, spawnPoints, trafficLightPositions] = createDrivingScenario()
    % createDrivingScenario Returns the drivingScenario defined in the Designer

    % Generated by MATLAB(R) 9.10 (R2021a) and Automated Driving Toolbox 3.3 (R2021a).
    % Generated on: 26-Jul-2024 12:56:49

    % Construct a drivingScenario object.
    scenario = drivingScenario;

    % Add all road segments
    roadCenters = [57.3 0.1 0; -6.8 0.1 0];
    marking = [laneMarking('Solid', 'Color', [0.98 0.86 0.36], 'Width', 0.01)
               laneMarking('DoubleDashed', 'Length', 2)
               laneMarking('Solid')];
    laneSpecification = lanespec(2, 'Width', 3, 'Marking', marking);
    road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

    roadCenters = [25.9 35.6 0; 25.9 -36.3 0];
    laneSpecification = lanespec(2);
    road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road1');

    spawnPoints = [
        -6.8 -1.5 0;  % Left lane, westbound
        -6.8  1.5 0;  % Right lane, eastbound
        25.9 -36.3 0; % Bottom lane, northbound
        25.9  36.3 0  % Top lane, southbound
    ];

    trafficLightPositions = [
        0 0 0;  % Center intersection
        % Add more positions if needed for additional intersections
    ];
end
